services:

  init-perms:
    image: busybox
    user: "0:0"
    volumes:
      - vault-data:/vault-data
      - vault-token:/vault-token
    command: sh -c "chown -R 100:100 /vault-data /vault-token"
    restart: "no"

  msr-vault-demo:
    image: ghcr.io/staillanibm/msr-vault-demo:${TAG:-latest}
    platform: linux/amd64
    container_name: msr-vault-demo
    ports:
      - "15555:5555"
    volumes:
      - ./application.properties.vault:/opt/softwareag/IntegrationServer/application.properties
      - ./vault/out/client_token:/tmp/client_token
      - ${TLS_CERT_PATH}:/tmp/fullchain.pem:ro
    env_file:
      - .env
    depends_on:
      vault-bootstrap:
        condition: service_completed_successfully
    healthcheck:
      interval: 5s
      retries: 24
      test: ["CMD-SHELL", "curl -o /dev/null -s -w '%{http_code}' http://localhost:5555 | grep -qE '^(200|3[0-9]{2})$'"]

  vault:
    image: hashicorp/vault:1.20
    platform: linux/amd64 
    container_name: vault
    user: "100:100"
    entrypoint: ["/bin/sh","-lc","exec vault server -config=/vault/config.hcl"]
    command: [] 
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=https://0.0.0.0:8200
    volumes:
      - ./vault/config.hcl:/vault/config.hcl:ro  
      - ./vault/bootstrap:/bootstrap:ro  
      - vault-data:/vault/data
      - ${TLS_CERT_PATH}:/vault/tls/fullchain.pem:ro
      - ${TLS_KEY_PATH}:/vault/tls/privkey.pem:ro
    restart: unless-stopped
    networks:
      default:
        aliases:
          - vault.sttlab.local  
    healthcheck:
      interval: 3s
      retries: 60
      test:
        [
          "CMD-SHELL",
          "vault status -address=https://127.0.0.1:8200 -tls-skip-verify >/dev/null 2>&1; ec=$$?; [ $$ec -le 3 ]"
        ]


  vault-bootstrap:
    image: willhallonline/ansible:latest   
    container_name: vault-bootstrap
    depends_on:
      vault:
        condition: service_healthy
    working_dir: /ansible
    environment:
      VAULT_ADDR: https://vault.sttlab.local:8200
      VAULT_KV_MOUNT: secret
      VAULT_KV_PATH: msr
      VAULT_TRANSIT_KEY: msr-key
      ANSIBLE_FORCE_COLOR: "1"
    volumes:
      - ./ansible:/ansible:ro              
      - ./vault/bootstrap:/bootstrap:ro    
      - ./vault/out:/out                   
    command: >
      ansible-playbook -i inventory playbook.yml -vvv
    restart: "no"


volumes:
  vault-data:
  vault-token: